#### 
#### use "Flu2009" dataset 
#### to estimate Rt

# loading packages
library(EpiEstim)
library(ggplot2)
library(incidence)

# load "Flu2009" data and view data
data("Flu2009")
head(Flu2009$incidence) # incidence data (dates & daily incidence number): PNAS 2011 paper
Flu2009$si_distr        # si_distr data: Nature 2005 paper
plot(Flu2009$si_distr)  # plot SI distribution (lognormal, gamma, weibull) 
Flu2009$si_data         # si_data (infector/secondary, type??): EID 2010 paper 

# plot incidence(y-axis) over time(x-axis)
plot(as.incidence(Flu2009$incidence$I, dates = Flu2009$incidence$dates))

####
#### Method 1, simplest, only need mean $ SD of serial interval
#### parametric_si

# estimate R, weekly(default), parametric serial interval
# flu mean & SD values from Nature 2005 paper
res_parametric_si <- estimate_R(Flu2009$incidence, method = "parametric_si", 
                                config = make_config(list(mean_si = 2.6, std_si = 1.5)))

# view R data.frame 
head(res_parametric_si$R)

# Rt (posterior mean, 95% CI) in the 2nd plot
plot(res_parametric_si, legend = FALSE)
# or only plot R 
# plot(res_parametric_si,"R")

####
#### Method 2, full distribution of serial interval
#### non_parametric_si

res_non_parametric_si <- estimate_R(Flu2009$incidence, method = "non_parametric_si",
                                    config = make_config(list(si_distr = Flu2009$si_distr)))
plot(res_non_parametric_si)

####
#### Method 3, integrate results over various distributions of serial interval 
#### uncertain_si

# to draw 
# the mean of the SI in a Normal(2.6,1), truncated at 1 and 4.2
# the sd of the SI in a Normal(1.5,0.5), truncated at 0.5 and 2.5
config <- make_config(list(mean_si = 2.6, std_mean_si = 1, min_mean_si = 1, max_mean_si = 4.2,
                           std_si = 1.5, std_std_si = 0.5, min_std_si = 0.5, max_std_si = 2.5))
res_uncertain_si <- estimate_R(Flu2009$incidence, method = "uncertain_si", 
                               config = config)
plot(res_uncertain_si)

####
#### Method 4, using data on pairs infector/secondary 
#### si_from_data

# fix the random seeds
MCMC_seed <- 1
overall_seed <- 2
# make_mcmc_control 
# creates a list of mcmc control parameters to be used in config$mcmc_control
# burnin, iteration times
mcmc_control <- make_mcmc_control(seed = MCMC_seed, burnin = 1000)
dist <- "G"  # fitting a Gamma distribution for the SI
config <- make_config(list(si_parametric_distr = dist, 
                           mcmc_control = mcmc_control,
                           seed = overall_seed,
                           n1 = 50,   # n1, size of samples of SI distributions to be drawn
                           n2 = 50))  # n2, size of samples drawn from the posterior distribution
res_si_from_data <- estimate_R(Flu2009$incidence, method = "si_from_data",
                               si_data = Flu2009$si_data,
                               config = config)
# The 3rd plot shows the posterior sample of SI distribution
# integrated over
plot(res_si_from_data)

####
#### Method 5, using samples
#### si_from_sample

# fix the random seeds
MCMC_seed <- 1
overall_seed <- 2
SI.fit <- coarseDataTools::dic.fit.mcmc(dat = Flu2009$si_data,
                                        dist = "G",
                                        # initial parameter value, scale $ shape for distribution
                                        init.pars = init_mcmc_params(Flu2009$si_data, "G"),
                                        burnin = 1000,
                                        # number of samples drawn from posterior(after burnin)
                                        n.samples = 5000,
                                        seed = MCMC_seed)
# output right format for estimate_R
# DI.fit 
# - an object generated by coarseDataTools::dic.fit.mcmc, 
# - containing posterior estimates of the serial interval distribution
# thin - only 1 in thin will be kept in posterior sample
si_samples <- coarse2estim(SI.fit, thin = 10)$si_sample
R_si_from_sample <- estimate_R(Flu2009$incidence,
                               method = "si_from_sample",
                               si_sample = si_samples,
                               # n2, size of samples drawn from the posterior distribution
                               config = make_config(list(n2=50, 
                                                         seed = overall_seed)))
plot(R_si_from_sample)

####
#### Overall infectivity
####
lambda <- overall_infectivity(Flu2009$incidence, Flu2009$si_distr)
par(mfrow=c(2,1))
plot(Flu2009$incidence, type = "s", xlab = "time (days)", ylab = "incidence")
title(main = "Epidemic curve")
plot(lambda, type = "s", xlab = "time (days)", ylab = "Infectivity")
title(main = "Overall infectivity")

